-- Seed users (clerk_id NULL for testing with mock auth)
INSERT INTO users (clerk_id, name, email, karma, is_admin) VALUES
  (NULL, 'Rahul Sharma', 'rahul.sharma@sitnagpur.siu.edu.in', 25, false),
  (NULL, 'Priya Patel', 'priya.patel@sitnagpur.siu.edu.in', 15, false),
  (NULL, 'Arjun Kumar', 'arjun.kumar@sitnagpur.siu.edu.in', 10, false);

-- Seed realistic campus items
INSERT INTO items (type, title, description, image_url, category, color, brand, tags, location_name, lat, lng, happened_at, status, hidden_details, poster_id) VALUES
  -- Lost items
  (
    'lost',
    'Black Earbuds Case',
    'Small black charging case for wireless earbuds, last seen near the library entrance',
    NULL,
    'electronics',
    'black',
    'unknown',
    ARRAY['earbuds', 'case', 'charging', 'wireless'],
    'Library',
    21.1458, 79.0882,
    NOW() - INTERVAL '2 hours',
    'open',
    '{"distinguishing_features": ["scratches on back", "slight dent on corner"], "contents": ["both earbuds inside"], "marks": ["sticker residue"], "condition": "used, minor wear"}',
    1
  ),
  (
    'lost',
    'Student ID Card',
    'Blue college ID card with photo, lost somewhere between hostel and canteen',
    NULL,
    'documents',
    'blue',
    NULL,
    ARRAY['id', 'card', 'student', 'identification'],
    'Canteen',
    21.1465, 79.0895,
    NOW() - INTERVAL '5 hours',
    'open',
    '{"distinguishing_features": ["laminated", "magnetic strip"], "contents": ["student photo", "ID number"], "marks": ["corner bent"], "condition": "slightly worn"}',
    2
  ),
  (
    'lost',
    'Blue Water Bottle',
    'Insulated steel water bottle with university sticker',
    NULL,
    'personal',
    'blue',
    'Milton',
    ARRAY['bottle', 'water', 'steel', 'insulated'],
    'Sports Ground',
    21.1472, 79.0868,
    NOW() - INTERVAL '1 day',
    'open',
    '{"distinguishing_features": ["dented bottom", "university logo sticker"], "contents": ["empty"], "marks": ["name written in marker"], "condition": "well used"}',
    3
  ),
  (
    'lost',
    'Scientific Calculator',
    'Casio scientific calculator in black pouch',
    NULL,
    'electronics',
    'black',
    'Casio',
    ARRAY['calculator', 'scientific', 'casio', 'study'],
    'Lab 3',
    21.1455, 79.0878,
    NOW() - INTERVAL '3 hours',
    'open',
    '{"distinguishing_features": ["solar panel", "graph functions"], "contents": ["calculator only"], "marks": ["name on back"], "condition": "good"}',
    1
  ),
  (
    'lost',
    'Laptop Charger',
    'Dell 65W laptop charger with frayed cable',
    NULL,
    'electronics',
    'black',
    'Dell',
    ARRAY['charger', 'laptop', 'dell', 'adapter'],
    'Main Building',
    21.1462, 79.0888,
    NOW() - INTERVAL '6 hours',
    'open',
    '{"distinguishing_features": ["65W rating", "frayed cable near plug"], "contents": ["adapter and cable"], "marks": ["tape on cable"], "condition": "used, cable damage"}',
    2
  ),
  
  -- Found items
  (
    'found',
    'Black Wireless Earbuds Case',
    'Found a small black case for wireless earbuds near the library stairs',
    'https://example.com/earbuds.jpg',
    'electronics',
    'black',
    'unknown',
    ARRAY['earbuds', 'case', 'charging', 'wireless', 'black'],
    'Library',
    21.1458, 79.0883,
    NOW() - INTERVAL '1.5 hours',
    'open',
    '{"distinguishing_features": ["scratched back panel", "small dent on right corner"], "contents": ["both earbuds present", "charging cable"], "marks": ["faded sticker mark on top"], "condition": "used condition with minor scratches"}',
    3
  ),
  (
    'found',
    'Set of Keys with Keychain',
    'Found a key ring with 3 keys and a small figurine keychain',
    'https://example.com/keys.jpg',
    'personal',
    'silver',
    NULL,
    ARRAY['keys', 'keychain', 'ring'],
    'Hostel Block A',
    21.1448, 79.0892,
    NOW() - INTERVAL '4 hours',
    'open',
    '{"distinguishing_features": ["3 keys total", "one brass key"], "contents": ["door key", "padlock key", "locker key"], "marks": ["cartoon keychain"], "condition": "normal wear"}',
    1
  ),
  (
    'found',
    'Red Umbrella',
    'Large red umbrella found near canteen',
    'https://example.com/umbrella.jpg',
    'personal',
    'red',
    NULL,
    ARRAY['umbrella', 'red', 'rain'],
    'Canteen',
    21.1466, 79.0896,
    NOW() - INTERVAL '8 hours',
    'at_desk',
    '{"distinguishing_features": ["automatic open button", "curved handle"], "contents": ["umbrella only"], "marks": ["small tear in fabric"], "condition": "good, minor tear"}',
    2
  ),
  (
    'found',
    'Gray Hoodie',
    'Found a gray zip-up hoodie left on bench',
    'https://example.com/hoodie.jpg',
    'clothing',
    'gray',
    'Adidas',
    ARRAY['hoodie', 'jacket', 'clothing', 'adidas'],
    'Sports Ground',
    21.1473, 79.0869,
    NOW() - INTERVAL '12 hours',
    'open',
    '{"distinguishing_features": ["size L", "zip closure"], "contents": ["phone in pocket"], "marks": ["adidas logo", "small stain on sleeve"], "condition": "worn"}',
    3
  ),
  (
    'found',
    'Brown Leather Wallet',
    'Found a brown wallet with some cards inside',
    'https://example.com/wallet.jpg',
    'personal',
    'brown',
    NULL,
    ARRAY['wallet', 'leather', 'brown'],
    'Main Building',
    21.1461, 79.0887,
    NOW() - INTERVAL '2 days',
    'at_desk',
    '{"distinguishing_features": ["bi-fold design", "coin pocket"], "contents": ["3 cards", "some cash"], "marks": ["worn edges"], "condition": "well used"}',
    1
  ),
  (
    'found',
    'Wired Headphones',
    'Black wired headphones with 3.5mm jack',
    'https://example.com/headphones.jpg',
    'electronics',
    'black',
    'Sony',
    ARRAY['headphones', 'wired', 'audio', 'sony'],
    'Lab 3',
    21.1456, 79.0879,
    NOW() - INTERVAL '10 hours',
    'open',
    '{"distinguishing_features": ["over-ear design", "coiled cable"], "contents": ["headphones only"], "marks": ["sony logo faded"], "condition": "used"}',
    2
  ),
  (
    'found',
    'Green Water Bottle',
    'Plastic water bottle, half full',
    'https://example.com/bottle.jpg',
    'personal',
    'green',
    'Tupperware',
    ARRAY['bottle', 'water', 'plastic'],
    'Canteen',
    21.1467, 79.0897,
    NOW() - INTERVAL '5 hours',
    'open',
    '{"distinguishing_features": ["flip-top lid", "measurements on side"], "contents": ["water inside"], "marks": ["name sticker peeling off"], "condition": "good"}',
    3
  ),
  (
    'found',
    'Notebook with Notes',
    'Spiral notebook with engineering notes',
    'https://example.com/notebook.jpg',
    'documents',
    'blue',
    NULL,
    ARRAY['notebook', 'notes', 'study', 'spiral'],
    'Library',
    21.1459, 79.0884,
    NOW() - INTERVAL '1 day',
    'open',
    '{"distinguishing_features": ["spiral binding", "100 pages"], "contents": ["handwritten notes", "diagrams"], "marks": ["name on first page"], "condition": "used, some pages torn"}',
    1
  ),
  (
    'found',
    'Black Backpack',
    'Small black backpack with laptop compartment',
    'https://example.com/backpack.jpg',
    'personal',
    'black',
    'Wildcraft',
    ARRAY['backpack', 'bag', 'laptop', 'black'],
    'Hostel Block A',
    21.1449, 79.0893,
    NOW() - INTERVAL '18 hours',
    'at_desk',
    '{"distinguishing_features": ["padded straps", "laptop sleeve"], "contents": ["some books", "water bottle"], "marks": ["wildcraft logo"], "condition": "good"}',
    2
  );
